package View;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Utils.FuncionarioModel;
import Utils.FuncionarioRelatorioDTO;
import Utils.HttpConnection;
import static View.DashboardAdministrador.DashboardAdministrador;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.awt.Component;
import java.awt.Dimension;
import java.io.FileOutputStream;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Oruam
 */
public class Funcionarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaFuncionarios
     */
    private void listarFuncionarios() {
        // Instância a classe de conexão
        HttpConnection httpConnection = new HttpConnection();

        // Chama o método para listar os funcionários cadastrados
        List<FuncionarioModel> funcionarios = httpConnection.listarFuncionarios();

        // Obtem o modelo da tabela
        DefaultTableModel Tabela = (DefaultTableModel) jTFuncionarios.getModel();

        // Limpa a tabela antes de adicionar os novos dados
        Tabela.setRowCount(0);
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        
        // Itera sobre a lista de funcionários e adiciona os dados na tabela
        for (FuncionarioModel funcionario : funcionarios) {
            // Verifica se o tipo de funcionário não é ADMINISTRADOR
                Object[] dados = {
                    funcionario.getNome_funcionario(), 
                    funcionario.getCpf_funcionario().replaceAll("(\\d{3})(\\.\\d{3}\\.\\d{3}-)(\\d{2})", "***$2**"),
                    funcionario.getEmail(),
                    funcionario.getTipoFuncionario().substring(0, 1).toUpperCase() + funcionario.getTipoFuncionario().substring(1).toLowerCase(),
                    funcionario.getData_emissao().format(formatter),
                    funcionario.getId_funcionario()
                };
                Tabela.addRow(dados);
        }
    }
    
    private final String emailFuncionario;
    private final String nomeFuncionario;
    public Funcionarios(String nomeFuncionario, String emailFuncionario) {
        initComponents();
        this.emailFuncionario = emailFuncionario;
        
        this.nomeFuncionario = nomeFuncionario;
        FlatLaf.registerCustomDefaultsSource("tableview");
        FlatMacDarkLaf.setup();
        
        Timer timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                // Atualiza os dados da tabela periodicamente
                listarFuncionarios();
            }
        }, 0, 5000); // Atualiza a cada 5000 ms (5 segundos)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jBGerarRelatorio = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTPesquisar = new javax.swing.JTextField();
        jLPesquisar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jBAdd = new javax.swing.JButton();
        jBEditar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTFuncionarios = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jCTipo = new javax.swing.JComboBox<>();
        jBLimparFiltros = new javax.swing.JButton();
        jLFundo = new javax.swing.JLabel();

        setBorder(null);
        setTitle("Funcionários");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setInheritsPopupMenu(true);
        setName("Tela Funcionário"); // NOI18N
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPanel2FocusLost(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel2MouseReleased(evt);
            }
        });
        jPanel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPanel2KeyReleased(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(238, 238, 238));
        jPanel9.setForeground(new java.awt.Color(233, 233, 233));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBGerarRelatorio.setBackground(new java.awt.Color(24, 24, 24));
        jBGerarRelatorio.setForeground(new java.awt.Color(204, 204, 204));
        jBGerarRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/DownloadIcon.png"))); // NOI18N
        jBGerarRelatorio.setText("Gerar relatório");
        jBGerarRelatorio.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(59, 59, 59)));
        jBGerarRelatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBGerarRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBGerarRelatorioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBGerarRelatorioMouseExited(evt);
            }
        });
        jBGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGerarRelatorioActionPerformed(evt);
            }
        });
        jPanel9.add(jBGerarRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 40));

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 620, 170, 60));

        jPanel3.setBackground(new java.awt.Color(24, 24, 24));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTPesquisar.setBackground(new java.awt.Color(24, 24, 24));
        jTPesquisar.setForeground(new java.awt.Color(204, 204, 204));
        jTPesquisar.setText("Pesquisar");
        jTPesquisar.setBorder(null);
        jTPesquisar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTPesquisarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTPesquisarFocusLost(evt);
            }
        });
        jTPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTPesquisarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTPesquisarMouseExited(evt);
            }
        });
        jTPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPesquisarActionPerformed(evt);
            }
        });
        jTPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTPesquisarKeyReleased(evt);
            }
        });
        jPanel3.add(jTPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 230, 20));

        jLPesquisar.setBackground(new java.awt.Color(40, 40, 40));
        jLPesquisar.setForeground(new java.awt.Color(204, 204, 204));
        jLPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/PesquisarIcon.png"))); // NOI18N
        jPanel3.add(jLPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 30, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 270, 40));

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));
        jPanel1.setForeground(new java.awt.Color(233, 233, 233));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBAdd.setBackground(new java.awt.Color(24, 24, 24));
        jBAdd.setForeground(new java.awt.Color(204, 204, 204));
        jBAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/AddIcon.png"))); // NOI18N
        jBAdd.setText("Cadastrar");
        jBAdd.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(59, 59, 59)));
        jBAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBAddMouseExited(evt);
            }
        });
        jBAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddActionPerformed(evt);
            }
        });
        jPanel1.add(jBAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 110, 30));

        jBEditar.setBackground(new java.awt.Color(24, 24, 24));
        jBEditar.setForeground(new java.awt.Color(204, 204, 204));
        jBEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/DetalhesIcon.png"))); // NOI18N
        jBEditar.setText("Visualizar");
        jBEditar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(59, 59, 59)));
        jBEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBEditarMouseExited(evt);
            }
        });
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jBEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 110, 30));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 720, 60));

        jPanel4.setBackground(new java.awt.Color(238, 238, 238));
        jPanel4.setForeground(new java.awt.Color(233, 233, 233));

        jTFuncionarios.setShowHorizontalLines(true);
        jTFuncionarios.setShowVerticalLines(false);
        jTFuncionarios.setGridColor(new java.awt.Color(51,51,51));
        jTFuncionarios.setBackground(new java.awt.Color(238, 238, 238));
        jTFuncionarios.setIntercellSpacing(new Dimension(0, 10));
        jTFuncionarios.setRowHeight(30);
        jTFuncionarios.setForeground(new java.awt.Color(51,51,51));
        jTFuncionarios.setSelectionBackground(new java.awt.Color(24,24,24));
        jTFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Cpf", "E-mail", "Tipo", "Data", "Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTFuncionarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTFuncionarios.setSelectionBackground(new java.awt.Color(102,102,102));   // Fundo quando selecionado

        JTableHeader header = jTFuncionarios.getTableHeader();
        header.setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel label = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                // Definir a borda do cabeçalho
                if (column == 0) { // Para a primeira coluna (Nome)
                    label.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 1, table.getGridColor())); // Linha horizontal embaixo e sem linha vertical
                }else if (column == 5) { // Para a ultima coluna (Data de emissão)
                    label.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, table.getGridColor())); // Linha horizontal embaixo e sem linha vertical
                }else {
                    label.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 1, table.getGridColor())); // Linha horizontal embaixo e linha vertical à esquerda
                }

                label.setHorizontalAlignment(SwingConstants.CENTER); // Centralizar o texto no cabeçalho
                return label;
            }
        });
        jTFuncionarios.setSelectionForeground(new java.awt.Color(204,204,204));
        jTFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTFuncionarios);
        if (jTFuncionarios.getColumnModel().getColumnCount() > 0) {
            jTFuncionarios.getColumnModel().getColumn(0).setPreferredWidth(200);
            jTFuncionarios.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTFuncionarios.getColumnModel().getColumn(2).setPreferredWidth(150);
            jTFuncionarios.getColumnModel().getColumn(3).setPreferredWidth(90);
            jTFuncionarios.getColumnModel().getColumn(4).setPreferredWidth(70);
            jTFuncionarios.getColumnModel().getColumn(5).setPreferredWidth(20);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, 490));

        jPanel5.setBackground(new java.awt.Color(238, 238, 238));
        jPanel5.setForeground(new java.awt.Color(233, 233, 233));

        jPanel7.setBackground(new java.awt.Color(24, 24, 24));

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Tipo");

        jCTipo.setBackground(new java.awt.Color(24, 24, 24));
        jCTipo.setForeground(new java.awt.Color(204, 204, 204));
        jCTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Funcionario", "Administrador" }));
        jCTipo.setBorder(null);
        jCTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCTipo.setOpaque(true);
        jCTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTipoActionPerformed(evt);
            }
        });
        jPanel1.add(jCTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, -1, 30));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCTipo, 0, 145, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jBLimparFiltros.setBackground(new java.awt.Color(24, 24, 24));
        jBLimparFiltros.setForeground(new java.awt.Color(204, 204, 204));
        jBLimparFiltros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/DeletarIcon.png"))); // NOI18N
        jBLimparFiltros.setText("Limpar filtros");
        jBLimparFiltros.setBorder(null);
        jBLimparFiltros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBLimparFiltros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBLimparFiltrosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBLimparFiltrosMouseExited(evt);
            }
        });
        jBLimparFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparFiltrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jBLimparFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jBLimparFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 190, 180));

        jLFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/FundoView.png"))); // NOI18N
        jPanel2.add(jLFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 1000));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTnomeActionPerformed

    private void JCgeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCgeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCgeneroActionPerformed

    private void JCtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCtipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCtipoActionPerformed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
  
    }//GEN-LAST:event_formKeyReleased

    private void jPanel2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel2KeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel2KeyReleased

    private void jPanel2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2FocusGained

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseReleased

    private void jTPesquisarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTPesquisarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPesquisarMouseExited

    private void jTPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTPesquisarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPesquisarMouseClicked

    private void jTPesquisarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTPesquisarFocusLost
        // TODO add your handling code here:
        if(jTPesquisar.getText().equals("")){
            jTPesquisar.setText("Pesquisar");
        }
    }//GEN-LAST:event_jTPesquisarFocusLost

    private void jTPesquisarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTPesquisarFocusGained
        // TODO add your handling code here:
        if(jTPesquisar.getText().equals("Pesquisar")){
            jTPesquisar.setText("");
        }
    }//GEN-LAST:event_jTPesquisarFocusGained

    private void jPanel2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel2FocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel2FocusLost
    
    private void filtrarTabela(String textoFiltro){
        DefaultTableModel modelo = (DefaultTableModel) jTFuncionarios.getModel();
        TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(modelo);
        jTFuncionarios.setRowSorter(obj);

        // Adiciona a flag (?i) para fazer a pesquisa ignorar maiúsculas e minúsculas
        obj.setRowFilter(RowFilter.regexFilter("(?i)" + textoFiltro));
    }
    
    private void jTPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTPesquisarKeyReleased
        // TODO add your handling code here:
        filtrarTabela(jTPesquisar.getText());
    }//GEN-LAST:event_jTPesquisarKeyReleased

    private void jTFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFuncionariosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFuncionariosMouseClicked

    private void jTPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPesquisarActionPerformed

    private void jCTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTipoActionPerformed
        // TODO add your handling code here:
        filtrarTabela(jCTipo.getSelectedItem().toString());
    }//GEN-LAST:event_jCTipoActionPerformed

    private void jBAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddActionPerformed
        // TODO add your handling code here:
        CadastrarFuncionario cadastrarFuncionario = new CadastrarFuncionario();
        DashboardAdministrador.add(cadastrarFuncionario);
        cadastrarFuncionario.setVisible(true);
        cadastrarFuncionario.setBounds(400, 0, 410, 724);
    }//GEN-LAST:event_jBAddActionPerformed

    private void jBAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAddMouseExited
        // TODO add your handling code here:
        jBAdd.setBackground(new java.awt.Color(24,24,24));
    }//GEN-LAST:event_jBAddMouseExited

    private void jBAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAddMouseEntered
        // TODO add your handling code here:
        jBAdd.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_jBAddMouseEntered

    private void jBEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBEditarMouseEntered
        // TODO add your handling code here:
        jBEditar.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_jBEditarMouseEntered

    private void jBEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBEditarMouseExited
        // TODO add your handling code here:
        jBEditar.setBackground(new java.awt.Color(24,24,24));
    }//GEN-LAST:event_jBEditarMouseExited

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        // TODO add your handling code here:
        int[] selectedRows = jTFuncionarios.getSelectedRows();

        if(selectedRows.length == 0){
            JOptionPane.showMessageDialog(null, "ERRO: selecione um funcionário.");
        }else if(selectedRows.length > 1){
            JOptionPane.showMessageDialog(null, "ERRO: selecione somente um funcionário.");
        }else{
            FuncionarioModel funcionarioSelecionado = new FuncionarioModel();
            funcionarioSelecionado.setTipoFuncionario(String.valueOf(jTFuncionarios.getValueAt(jTFuncionarios.getSelectedRow(), 3)));
            funcionarioSelecionado.setEmail(String.valueOf(jTFuncionarios.getValueAt(jTFuncionarios.getSelectedRow(), 2)));
            
            if (!funcionarioSelecionado.getTipoFuncionario().equals("Administrador") || funcionarioSelecionado.getEmail().equals(this.emailFuncionario)){
                funcionarioSelecionado.setId_funcionario(Integer.parseInt(String.valueOf(jTFuncionarios.getValueAt(jTFuncionarios.getSelectedRow(), 5))));

                VisualizarFuncionario visualizarFuncionario = new VisualizarFuncionario(funcionarioSelecionado.getId_funcionario(), this.emailFuncionario);
                DashboardAdministrador.add(visualizarFuncionario);
                visualizarFuncionario.setVisible(true);
                visualizarFuncionario.setBounds(400, 0, 410, 744);
            }else{
                JOptionPane.showMessageDialog(null, "ERRO: ação não permitida.");
            }
        }
    }//GEN-LAST:event_jBEditarActionPerformed

    private void jBGerarRelatorioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBGerarRelatorioMouseEntered
        // TODO add your handling code here:
        jBGerarRelatorio.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_jBGerarRelatorioMouseEntered

    private void jBGerarRelatorioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBGerarRelatorioMouseExited
        // TODO add your handling code here:
        jBGerarRelatorio.setBackground(new java.awt.Color(24,24,24));
    }//GEN-LAST:event_jBGerarRelatorioMouseExited
    
    private void salvarRelatorio(byte[] relatorio, String nomePadraoArquivo) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Salvar Relatório");
        fileChooser.setSelectedFile(new java.io.File(nomePadraoArquivo)); // Define o nome padrão do arquivo

        // Mostra o diálogo de salvar
        int userSelection = fileChooser.showSaveDialog(null);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            java.io.File arquivoSelecionado = fileChooser.getSelectedFile();
            String caminhoArquivo = arquivoSelecionado.getAbsolutePath();

            // Garante que o arquivo tenha a extensão .pdf
            if (!caminhoArquivo.toLowerCase().endsWith(".pdf")) {
                caminhoArquivo += ".pdf";
            }

            try (FileOutputStream fos = new FileOutputStream(caminhoArquivo)) {
                // Escreve o conteúdo do byte[] no arquivo
                fos.write(relatorio);
                fos.flush();
                JOptionPane.showMessageDialog(null, "Relatório salvo com sucesso em: " + caminhoArquivo);
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Erro ao salvar o relatório: " + e.getMessage());
            }
        }
    }
    
    private void jBGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGerarRelatorioActionPerformed
        // Cria o DTO para o relatório de funcionários
        FuncionarioRelatorioDTO relatorioDTO = new FuncionarioRelatorioDTO();

        // Lista para armazenar os funcionários
        List<FuncionarioModel> funcionarios = new ArrayList<>();

        // Obtém o modelo da tabela
        DefaultTableModel tableModel = (DefaultTableModel) jTFuncionarios.getModel();  // Assumindo que a tabela de funcionários é jTFuncionarios

        // Itera sobre as linhas da tabela para criar os objetos FuncionarioModel
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            FuncionarioModel funcionario = new FuncionarioModel();

            // Configura as propriedades do funcionário
            funcionario.setNome_funcionario((String) tableModel.getValueAt(i, 0)); // Nome
            funcionario.setCpf_funcionario((String) tableModel.getValueAt(i, 1)); // CPF
            funcionario.setEmail((String) tableModel.getValueAt(i, 2)); // E-mail
            funcionario.setTipoFuncionario((String) tableModel.getValueAt(i, 3).toString().toUpperCase()); // Tipo de Funcionário
            
            String dataEmissaoString = (String) tableModel.getValueAt(i, 4); // Data do pedido como String
            LocalDate dataEmissao = LocalDate.parse(dataEmissaoString, DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            funcionario.setData_emissao(dataEmissao); // Nascimento
            
            funcionario.setId_funcionario((int) tableModel.getValueAt(i, 5)); // ID

            // Adiciona o funcionário à lista
            funcionarios.add(funcionario);
        }

        // Adiciona os funcionários à lista do relatório
        relatorioDTO.setFuncionarios(funcionarios);

        // Configura o nome do administrador no FuncionarioModel
        FuncionarioModel administrador = new FuncionarioModel();
        administrador.setNome_funcionario(this.nomeFuncionario); // Substitua pelo nome real do administrador
        relatorioDTO.setAdministrador(administrador);

        // Chama o método para gerar o relatório
        HttpConnection httpConnection = new HttpConnection();

        // Aqui você vai enviar o JSON dinâmico
        FuncionarioRelatorioDTO response = httpConnection.gerarRelatorioFuncionarios(relatorioDTO);

        if (response.getRelatorio() != null) {
            // Define o nome padrão do arquivo
            String nomePadraoArquivo = "RelatorioFuncionarios.pdf";

            // Salva o relatório no sistema
            salvarRelatorio(response.getRelatorio(), nomePadraoArquivo);
        } else {
            JOptionPane.showMessageDialog(null, "ERRO: falha ao tentar gerar o relatório de funcionários.");
        }
    }//GEN-LAST:event_jBGerarRelatorioActionPerformed

    private void jBLimparFiltrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLimparFiltrosMouseEntered
        // TODO add your handling code here:
        jBLimparFiltros.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_jBLimparFiltrosMouseEntered

    private void jBLimparFiltrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLimparFiltrosMouseExited
        // TODO add your handling code here:
        jBLimparFiltros.setBackground(new java.awt.Color(24,24,24));
    }//GEN-LAST:event_jBLimparFiltrosMouseExited

    private void jBLimparFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparFiltrosActionPerformed
        // TODO add your handling code here:
        filtrarTabela("");
    }//GEN-LAST:event_jBLimparFiltrosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdd;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBGerarRelatorio;
    private javax.swing.JButton jBLimparFiltros;
    private javax.swing.JComboBox<String> jCTipo;
    private javax.swing.JLabel jLFundo;
    private javax.swing.JLabel jLPesquisar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTFuncionarios;
    private javax.swing.JTextField jTPesquisar;
    // End of variables declaration//GEN-END:variables
}
