/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author Oliveira
 */
public class VisualizarFotoAnimal extends javax.swing.JInternalFrame {

    /**
     * Creates new form VisualizarFoto
     */
    
    public VisualizarFotoAnimal(byte[] imagemBytes) {
        initComponents();
        setImage(imagemBytes);  // Adiciona a imagem ao JLabel
    }

    private void setImage(byte[] imagemBytes) {
        try {
            // Converte bytes em BufferedImage
            ByteArrayInputStream bis = new ByteArrayInputStream(imagemBytes);
            BufferedImage img = ImageIO.read(bis);
            
            // Obtenha o tamanho original da imagem
            int originalWidth = img.getWidth();
            int originalHeight = img.getHeight();

            // Defina as dimensões da janela de visualização (400x400)
            int targetWidth = 400;
            int targetHeight = 400;

            // Mantém a proporção da imagem
            float widthRatio = (float) targetWidth / originalWidth;
            float heightRatio = (float) targetHeight / originalHeight;
            float ratio = Math.min(widthRatio, heightRatio);  // Mantém a menor razão

            // Calcula a nova largura e altura, mantendo a proporção
            int newWidth = (int) (originalWidth * ratio);
            int newHeight = (int) (originalHeight * ratio);

            // Redimensiona a imagem
            Image scaledImg = img.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);

            // Define o ícone redimensionado no JLabel
            jLFoto.setIcon(new ImageIcon(scaledImg));

            // Ajusta o tamanho do JLabel para a imagem
            jLFoto.setPreferredSize(new Dimension(newWidth, newHeight));
            jLFoto.setText("");  // Remove o texto do JLabel
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao carregar a imagem.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLFoto = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setTitle("Visualizar Foto");

        jLFoto.setHorizontalAlignment(SwingConstants.CENTER);
        jLFoto.setPreferredSize(new Dimension(400, 400)); // Define um tamanho fixo

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLFoto;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
